Repository develeep/Algorithm_study_7-2team, pull requests merged in 2025-04, with the labels that each got.

#2 Create test.txt
  test.txt
Labels: REFACTOR, COMPARE, FIX

#7 [Solve] : [BOJ] 7568 - 덩치 문제 해결
  minsun/BOJ/7568/sol.py
Labels: SOLVE, REVIEW

#4 제목 : [Solve] : [BOJ] 11559 - 뿌요뿌요 문제 해결
  comet/BOJ/11559/input.txt
  comet/BOJ/11559/sol.py
Labels: SOLVE, REVIEW

#8 [Solve] : 덩치 / 뿌요뿌요 문제 해결
  Minwoo/BOJ/11559/sol.py
  Minwoo/BOJ/7568/sol.py
Labels: SOLVE, REVIEW

#11 [Solve] : [BOJ] 11559 - 백준 뿌요뿌요 문제 해결
  seunghoon/BOJ/11559/sol.py
Labels: SOLVE, REFACTOR, REVIEW

#9 [Solve]: 7568번 덩치 문제 해결
  ImSeoHyun/BOJ/1244/sol.py
  ImSeoHyun/BOJ/2491/sol.py
  ImSeoHyun/BOJ/2635/sol.py
  ImSeoHyun/BOJ/7568/sol.py
  ImSeoHyun/BOJ/수열/sol.py
Labels: SOLVE

#6 [Solve] : 덩치 문제 해결
  JYJ/BOJ/7568/sol.py
Labels: SOLVE, REVIEW

#15 [Solve] : [BOJ] 11559- 뿌요뿌요 문제풀이
  jinhyeon/BOJ/11559/sol.py
Labels: SOLVE, REVIEW

#16 [Solve] : 뿌여뿌요
  hsr/boj/sol.py
Labels: SOLVE, REVIEW

#21 Boj/1018
  JYJ/BOJ/1018/sol.py
  JYJ/BOJ/2578/sol.py
  JYJ/BOJ/7568/sol.py
Labels: SOLVE, REVIEW

#13 [Solve] : [BOJ] 7568 - 덩치 문제해결
  donghwan/BOJ/7568/sol.py
  donghwan/PGM/commitfile.txt
  donghwan/SWEA/commitfile.txt
Labels: SOLVE

#23 [Solve] : 색종이 문제 해결
  minsun/BOJ/2563/sol.py
Labels: SOLVE, REVIEW

#24 [Solve]: [BOJ] 2559 - 수열 문제 해결
  minsun/BOJ/2559/sol.py
Labels: SOLVE, REVIEW, 민선

#26 [Solve] : [BOJ] 창고 다각형 문제 해결
  Minwoo/BOJ/2304/sol.py
Labels: SOLVE, REVIEW, 민우

#28 [Solve] : [BOJ] 2491 - 수열 문제 해결
  Minwoo/BOJ/2491/sol.py
Labels: SOLVE, REVIEW, 민우

#29 [solve]: 덩치 7568 문제해결
  minseo/7568/sol.py
Labels: SOLVE, REVIEW, 민서

#30 [Solve] : 2559 수열 문제해결
  minseo/2559/sol.py
Labels: SOLVE, REVIEW, 민서

#36 [solve]:1789 문제 해결
  minseo/1789/sol.py
Labels: SOLVE, REVIEW, 민서

#38 [solve]: 14501 퇴사 문제해결
  minseo/14501/sol.py
Labels: SOLVE, REVIEW, 민서

#40 [solve] : [swea] 풍선팡, 파리퇴치, 특별한 정렬 (**재시험 준비**)
  ImSeoHyun/SWEA/특별한 정렬/sol.py
  ImSeoHyun/SWEA/파리퇴치/sol.py
  ImSeoHyun/SWEA/풍선팡/sol.py
Labels: 서현

#41 [Solve] : [BOJ] 11399 - ATM 문제 해결
  Minwoo/BOJ/11399/sol.py
Labels: SOLVE, REVIEW, 민우

#42 [Solve] : [BOJ] 12927 배수 스위치 - 문제 해결
  Minwoo/BOJ/12927/sol.py
Labels: SOLVE, REVIEW, 민우

#45 [Solve] : [BOJ] 2839 설탕배달 - 문제 해결
  Minwoo/BOJ/2839/sol.py
Labels: SOLVE, REVIEW, 민우

#49 [Solve] : [BOJ] 2527 - 직사각형 문제풀이
  kimchaejun/BOJ/2491/sol.py
  kimchaejun/BOJ/2527/sol.py
  kimchaejun/BOJ/7568/sol.py
Labels: SOLVE, REVIEW, 채준

#44 [Solve] : [BOJ] 7568 문제 해결
  kimchaejun/BOJ/7568/sol.py
Labels: SOLVE, COMPARE, 채준

#31 [Solve] : 1181 문제 해결
  minseo/1181/sol.py
Labels: SOLVE, REVIEW, 민서

#33 [solve] 11650 문제해결
  minseo/11650/sol.py
Labels: SOLVE, REVIEW, 민서

#35 [solve] 2751 문제 해결
  minseo/2751/sol.py
Labels: SOLVE, REVIEW, 민서

#37 [solve]:2108 통계학 문제 해결
  minseo/2108/sol.py
Labels: SOLVE, REVIEW, 민서

#51 [Solved] : BOJ/2133 타일 채우기 - 문제풀이
  comet/BOJ/1799/sol.py
  comet/BOJ/2133/sol.py
  comet/BOJ/2293/sol.py
  comet/BOJ/3954/sol.py
Labels: SOLVE, 혜성

#52 [Solve] 퇴사2 문제 해결
  .idea/Algorithm_study_7-2team.iml
  .idea/misc.xml
  jinhyeon/BOJ/15486/sol.py
Labels: SOLVE, REVIEW, 진현

#53 [solve]:10158문제해결
  minseo/BOJ/10158/sol.py
Labels: SOLVE, REVIEW, 민서

#54 [Solve] : [BOJ] 10158 개미-문제해결
  JYJ/BOJ/10158/sol.py
Labels: SOLVE, REVIEW, 용준

#55 [Solve] : [BOJ] 10158 개미 문제 해결
  minsun/BOJ/10158/sol.py
Labels: FAIL, REVIEW, 민선

#56 [Solve] : 14501 퇴사
  hsr/boj/14501 퇴사/sol.py
  hsr/boj/뿌요뿌요/sol.py
Labels: SOLVE, REVIEW, 상래

#62 [Solve] : [BOJ] 16918 봄버맨 문제 해결
  kimchaejun/BOJ/16918/sol.py
Labels: SOLVE, REVIEW, 채준

#64 [fail]16918 봄버맨
  minseo/BOJ/16918/sol.py
Labels: FAIL, REVIEW, 민서

#70 [Solve] : [BOJ] 1347 미로만들기 - 문제 해결
  Minwoo/BOJ/1347/sol.py
Labels: SOLVE, REVIEW, 민우

#93 [Solve] : [SWEA] 22399 - 쉬운 당근 포장
  minsun/SWEA/22399/sol.py
Labels: SOLVE, REVIEW, 민선

#85 [Solve] : [BOJ] - 색종이 문제 해결
  JYJ/BOJ/2563/sol.py
Labels: SOLVE, COMPARE, 용준

#74 [Solve] : [BOJ] 미로만들기
  JYJ/BOJ/1347/sol.py
Labels: SOLVE, COMPARE, 용준

#59 [Fail] : [BOJ] 1959 달팽이 3 - 해결 중
  Minwoo/BOJ/1959/sol.py
Labels: FAIL, COMPARE, 민우

#65 [Solve]: 보물섬 문제해결
  jinhyeon/BOJ/2589/sol.py
Labels: SOLVE, REVIEW, 진현

#66 [Solve] : 9084 동전 문제 해결
  jinhyeon/BOJ/9084/sol.py
Labels: SOLVE, REVIEW, 진현

#68 [Solve] : [BOJ] 16918 봄버맨 - 문제해결
  Minwoo/BOJ/16918/sol.py
Labels: SOLVE, REVIEW, 민우

#47 [Solve] : [BOJ] 13305 주유소 - 문제 해결
  Minwoo/BOJ/13305/sol.py
Labels: SOLVE, REVIEW, 민우

#71 [solve] 듣보잡 해결
  ImSeoHyun/BOJ/1347/sol.py
  ImSeoHyun/BOJ/1764/sol.py
Labels: SOLVE, 서현

#73 [Solve] : [BOJ] 1347 미로 만들기 문제 해결
  kimchaejun/BOJ/1347/sol.py
Labels: SOLVE, REVIEW, COMPARE, 채준

#75 [Solve] 1347 미로만들기 문제 해결
  minseo/BOJ/1347/sol.py
Labels: SOLVE, REVIEW, 민서

#76 Boj/20056 -마법사 상어와 파이어볼
  hsr/boj/20056 마법사 상어와 파이어볼/20056.마법사 상어와 파이어볼.py
Labels: SOLVE, REVIEW, 상래

#77 [Solve] : 마법사 상어와 파이어볼 문제 해결
  JJangDongHyeon/20056/sol.py
Labels: SOLVE, REVIEW, 동현

#78 [Solve] : [BOJ] 20056 마법사 상어와 파이어볼 - 문제 해결
  Minwoo/BOJ/20056/sol.py
Labels: SOLVE, REVIEW, 민우

#79 [slove] : [BOJ] 7568 덩치 - 문제 해결
  jongbin/boj/16918/sol.py
  jongbin/boj/7568/sol.py
Labels: SOLVE, REVIEW, 종빈

#81 [Solve][BOJ] 칠무해 문제 해결
  minseo/BOJ/14729/sol.py
Labels: SOLVE, REVIEW, 민서

#86 [Solve] : [BOJ] 16236 아기상어 - 문제 해결
  Minwoo/BOJ/16236/sol.py
Labels: SOLVE, REVIEW, 민우

#88 [Solve] : [BOJ] 1244 스위치 켜고 끄기 문제 해결
  minsun/BOJ/1244/1244.py
Labels: SOLVE, COMPARE, 민선

#92 [Solve] : [SWEA] 22399 쉬운 당근 포장하기 - 문제 해결
  Minwoo/SWEA/22399/sol.py
Labels: SOLVE, REFACTOR, REVIEW, 민우

#125 [Solve] : [BOJ] 18870 - 좌표압축 문제 해결
  kimchaejun/BOJ/18870/sol.py
Labels: SOLVE, REFACTOR, REVIEW, 채준

#134 [Solve] : [BOJ] 14442 벽 부수고 이동하기2 - 문제해결
  Minwoo/BOJ/14442/sol_refactor.py
Labels: SOLVE, REFACTOR, REVIEW, 민우

#90 [Solved] : SWEA/5643 키 순서 문제 해결
  comet/SWEA/5643/sol.py
Labels: SOLVE, REVIEW, 혜성

#91 [Solve] : [SWEA] 22399 - 쉬운 당근 포장 문제 해결
  kimchaejun/BOJ/2149/sol.py
  kimchaejun/SWEA/22399/sol.py
Labels: SOLVE, REVIEW, 채준

#89 [Solve] : [BOJ] 2149 - 암호해독 문제 해결
  kimchaejun/BOJ/2149/sol.py
Labels: SOLVE, REVIEW, 채준

#94 [Solve] : [BOJ] 6593 상범 빌딩 - 문제 해결
  Minwoo/BOJ/6593/sol.py
Labels: SOLVE, REVIEW, 민우

#95 [Solve] : [SWEA] 22399 - 쉬운 당근 포장
  minsun/SWEA/22399/sol.py
Labels: SOLVE, REVIEW, 민선

#103 [Solve] : BOJ 10789 - 세로 읽기 문제 해결
  minsun/BOJ/10789/sol.py
Labels: SOLVE, REVIEW, 민선

#107 [Solve] : [BOJ] 10026 - 적록색약 문제 해결
  minsun/BOJ/10026/sol.py
Labels: SOLVE, COMPARE, 민선

#106 [Solve] : [BOJ] 10026 적록색약 - 문제 해결
  Minwoo/BOJ/10026/sol.py
Labels: SOLVE, REVIEW, 민우

#104 [Solve] : [SWEA] 22654 차윤이의 RC카 - 문제해결
  JYJ/SWEA/22654/sol.py
Labels: SOLVE, REVIEW, 용준

#117 [Solved] : BOJ/10942 문제해결
  comet/BOJ/10942/sol.py
Labels: SOLVE, REVIEW, 혜성

#133 [Solved] : SWEA/3951 CRT 문제 해결
  comet/SWEA/3951/sol.py
Labels: SOLVE, 혜성

#96 [Solve] : [BOJ] 2167 - 2차원 배열의 합 문제 해결
  minsun/BOJ/2167/sol.py
Labels: SOLVE, REVIEW, 민선

#97 [BOJ] : 17406 배열 돌리기 문제 해결
  comet/BOJ/17406/sol.py
Labels: SOLVE, REVIEW, 혜성

#98 [Solve] : [BOJ] 13305 - 주유소 문제해결
  minsun/BOJ/13305/sol.py
Labels: SOLVE, REVIEW, 민선

#100 [Solve] : [BOJ] 2206 벽 부수고 이동하기 - 문제 해결
  Minwoo/BOJ/2206/sol.py
Labels: SOLVE, REVIEW, 민우

#101 [Solve] : [SWEA] 22399 쉬운 당근 포장 - 문제 해결
  JYJ/SWEA/22399/sol.py
Labels: SOLVE, REVIEW, 용준

#102 [Solve] : [BOJ] 1600 말이 되고픈 원숭이 - 문제 해결
  Minwoo/BOJ/1600/sol.py
Labels: SOLVE, REVIEW, 민우

#99 [Solve] : [BOJ] 2999 비밀 이메일 - 문제 해결
  JYJ/BOJ/2999/sol.py
Labels: SOLVE, REVIEW, 용준

#105 [Solve] : [SWEA] 22654 차윤이의 RC카 - 문제 해결
  Minwoo/SWEA/22654/sol.py
Labels: SOLVE, REVIEW, 민우

#108 [Solve] : [BOJ] 2527 - 직사각형 문제 해결
  minsun/BOJ/2527/sol.py
Labels: SOLVE, REVIEW, 민선

#109 [Solved] : [BOJ] 17472 다리 만들기 2 문제 해결
  comet/BOJ/17472/sol.py
Labels: SOLVE, REVIEW, 혜성

#113 [Solve] : [SWEA] 23795 - 우주 괴물 문제 해결
  minsun/SWEA/23795/sol.py
Labels: SOLVE, REVIEW, 민선

#115 [Solve] : [SWEA] 22654 - 차윤이의 RC카 문제 해결
  minsun/SWEA/22654/sol.py
Labels: SOLVE, REVIEW, 민선

#114 [Solve] : [SWEA] 22407 - 색칠하기 3 문제 해결
  minsun/SWEA/22407/sol.py
Labels: SOLVE, REVIEW, 민선

#110 [Solve] : [BOJ] 1652 - 누울 자리를 찾아라 문제 해결
  minsun/BOJ/1652/sol.py
Labels: SOLVE, REVIEW, 민선

#112 [Solve] : [SWEA] 22683 나무 베기 - 문제 해결
  Minwoo/SWEA/22683/sol.py
Labels: SOLVE, REVIEW, 민우

#116 [Solve]:[BOJ] 1996 지뢰찾기 문제 해결
  kimchaejun/BOJ/1996/sol.py
Labels: SOLVE, REVIEW, 채준

#118 [Solve] : [BOJ] 11723-집합문제해결
  kimchaejun/BOJ/11723/sol.py
Labels: SOLVE, REVIEW, 채준

#119 [Solve] : 2567 색종이 - 2 문제해결
  JYJ/BOJ/2567/sol.py
Labels: SOLVE, REVIEW, 용준

#121 [Solve] : [BOJ] 9095 - 1,2,3 더하기 문제풀이
  jinhyeon/BOJ/9095/sol.py
Labels: SOLVE, REVIEW, 진현

#120 [Solve] : [SWEA] 4012 - 요리사 문제풀이
  jinhyeon/SWEA/4012/sol.py
Labels: SOLVE, REVIEW, 진현

#122 [Solve] : [SWEA] 5643 - 키 순서 문제풀이
  jinhyeon/SWEA/5643/sol.py
Labels: SOLVE, REVIEW, 진현

#123 [Solve] : [BOJ] 1520 - 내리막길 문제풀이
  jinhyeon/BOJ/1520/sol.py
Labels: SOLVE, REVIEW, 진현

#124 [Solve] : [BOJ] 12891 DNA 비밀번호 - 문제 해결
  JYJ/BOJ/12891/sol.py
Labels: SOLVE, REVIEW, 용준

#126 [Solve] : [BOJ] 16985 - Maze 문제풀이
  jinhyeon/BOJ/16985/sol.py
Labels: SOLVE, REVIEW, 진현

#127 [Solved] : SWEA/3950 괄호 문제풀이
  comet/SWEA/3950/sol.py
Labels: SOLVE, 혜성

#128 [Solve] : [BOJ] 2630 - 색종이 만들기 문제 해결
  kimchaejun/BOJ/2630/sol.py
Labels: SOLVE, REVIEW, 채준

#136 [Solve] : [BOJ] 14889 스타트와 링크 - 문제 해결
  JYJ/BOJ/14889/sol.py
Labels: SOLVE, REVIEW, 용준

#137 [Solve] : [BOJ] 2573 - 빙산 문제풀이
  jinhyeon/BOJ/2573/sol.py
Labels: SOLVE, REVIEW, 진현

#138 [Solve] : [BOJ] 9466 - 텀 프로젝트 문제풀이
  jinhyeon/BOJ/9466/sol.py
Labels: SOLVE, REVIEW, 진현

#140 [Solve] : [BOJ] 1449 - 수리공 항승 문제 해결
  kimchaejun/BOJ/1449/sol.py
Labels: SOLVE, REVIEW, 채준

#150 [Solve] : [BOJ] 10163 - 색종이 문제해결
  minsun/BOJ/10163/sol.py
Labels: SOLVE, REVIEW, 민선

#141 [Solve] : [BOJ] 7576 토마토 - 문제 해결
  JYJ/BOJ/7576/sol.py
Labels: SOLVE, COMPARE, 용준

#69 [Fail] : [BOJ] 16918 봄버맨 - 해결 중
  minsun/BOJ/16918/sol.py
Labels: COMPARE, 민선

#139 [Solve] : [BOJ] 3085 - 사탕게임 문제해결
  minsun/BOJ/3085/sol.py
Labels: SOLVE, REVIEW, 민선

#142 [Solve] : [BOJ] 2108 - 통계학 문제해결
  kimchaejun/BOJ/2108/sol.py
Labels: SOLVE, REVIEW, 채준

#143 [Solved] : BOJ/2011 암호코드 문제해결
  comet/BOJ/2011/sol.py
Labels: SOLVE, REVIEW, 혜성

#145 [Solve] : [BOJ] 2617 - 구슬찾기 문제풀이
  jinhyeon/BOJ/2617/sol.py
Labels: SOLVE, REVIEW, 진현

#146 [Solve]: [BOJ] 2660 회장뽑기 문제풀기
  jinhyeon/BOJ/2660/sol.py
Labels: SOLVE, REVIEW, 진현

#148 [solve]: [BOJ] / 1238번 파티 문제풀이
  seunghoon/BOJ/sol.py
Labels: SOLVE, REVIEW, 승훈

#149 [Solve] : [BOJ] 14472 - Refreshment Area 문제 해결
  kimchaejun/BOJ/14472/sol.py
Labels: SOLVE, REVIEW, 채준

#153 [Solved] : BOJ/14499 주사위 굴리기 문제 해결
  comet/BOJ/14499/sol.py
Labels: SOLVE, REVIEW, 혜성

#154 [Solved] : BOJ/14500 테트로미노
  comet/BOJ/14500/sol.py
Labels: SOLVE, REVIEW, 혜성

#155 [Solve] : [BOJ] 2635 - 수 이어가기 문제 해결
  kimchaejun/BOJ/2635/sol.py
Labels: SOLVE, REVIEW, 채준

#156 [Solve] : [BOJ] 2493 탑 - 문제 해결
  JYJ/BOJ/2493/sol.py
Labels: SOLVE, REVIEW, 용준

#157 [Solve]: [BOJ] 1600 - 말이 되고픈 원숭이 문제 해결
  jinhyeon/BOJ/2116/sol.py
Labels: SOLVE, REVIEW, 진현

#159 [Solve] : [BOJ] 2636 치즈- 문제 해결
  Minwoo/BOJ/2636/sol.py
Labels: SOLVE, REVIEW, 민우

#160 [Solve] : [BOJ] 2635 수 이어가기 - 문제 해결
  JYJ/BOJ/2635/sol.py
Labels: SOLVE, REVIEW, 용준

#158 [Solve] : [BOJ] 11659 구간 합 구하기4 - 문제 해결
  Minwoo/BOJ/11569/sol.py
Labels: SOLVE, REVIEW, 민우

#162 [Solve] : [BOJ] 2167 2차원 배열의 합 - 문제 해결
  Minwoo/BOJ/2167/sol.py
Labels: SOLVE, REVIEW, 민우

#164 [Solve] : [BOJ] 2589 보물섬 - 문제 해결
  Minwoo/BOJ/2589/sol.py
Labels: SOLVE, REVIEW, 민우

#163 [Solve] : [BOJ] 11660 구간 합 구하기 5 - 문제 해결
  Minwoo/BOJ/11660/sol.py
Labels: SOLVE, REVIEW, 민우

#167 [Solve] : [BOJ] 1331 나이트 투어 - 문제 해결
  Minwoo/BOJ/1331/sol.py
Labels: SOLVE, REVIEW, 민우

#168 [Solve] : [BOJ] 1913 - 달팽이 문제해결 🐌
  minsun/BOJ/1913/sol.py
Labels: SOLVE, REVIEW, 민선

#170 [Solve] : [BOJ] 2589 보물섬 - 문제 해결
  JYJ/BOJ/2589/sol.py
Labels: SOLVE, COMPARE, 용준

#181 [Solve] : [BOJ] 2116 - 주사위 쌓기 문제 해결
  kimchaejun/BOJ/2116/sol.py
Labels: SOLVE, REFACTOR, REVIEW, 채준

#194 [Solve] : [BOJ] 2567 색종이-2
  Minwoo/BOJ/2567/sol.py
Labels: SOLVE, REVIEW, 민우

#200 [Solve] : [BOJ] 2116 주사위 쌓기 - 문제 해결
  JYJ/BOJ/2116/sol.py
Labels: SOLVE, REVIEW, 용준

#203 [Solve]: [BOJ] 신기한 소수 문제 해결
  jinhyeon/BOJ/2023/sol.py
Labels: SOLVE, REVIEW, 진현

#215 [Solve]:[BOJ] 14696 2477 2605 문제해결
  minsun/BOJ/14696/sol.py
  minsun/BOJ/2477/sol.py
  minsun/BOJ/2605/sol.py
Labels: SOLVE, REVIEW, 민선

#217 [Solve] : [BOJ] 11403 경로 찾기 - 문제 해결
  Minwoo/BOJ/11403/sol.py
Labels: SOLVE, REVIEW, 민우

#216 [Solve]:[BOJ] 아기 상어 문제 해결
  jinhyeon/BOJ/16236/sol.py
Labels: SOLVE, REVIEW, 진현

#171 [Solve] : [BOJ] 14003 가장 긴 증가하는 부분 수열 5 문제풀이
  seunghoon/BOJ/14003/sol.py
Labels: SOLVE, REVIEW, 승훈

#172 [solve]2669번 문제해결
  minseo/BOJ/2669/sol.py
Labels: SOLVE, REVIEW, 민서

#177 [Solve] : [BOJ] 16955 - 오목, 이길 수 있을까? 문제해결
  minsun/BOJ/16955/sol.py
Labels: SOLVE, REVIEW, 민선

#182 [Solve] : [BOJ] 10157 자리배정 - 문제 해결
  JYJ/BOJ/10157/sol.py
Labels: SOLVE, REVIEW, 용준

#186 [Solve] : [BOJ] 2567 - 색종이 2 문제해결
  minsun/BOJ/2567/sol.py
Labels: SOLVE, REVIEW, 민선

#191 [Solve] : [BOJ] 10814 나이순 정렬
  Minwoo/BOJ/10814/sol.py
Labels: SOLVE, REVIEW, 민우

#190 [Solve] : [BOJ] 31924 - 현대모비스 특별상의 주인공은? 2
  minsun/BOJ/31924/sol.py
Labels: SOLVE, REVIEW, 민선

#187 [Solve] : [BOJ] 1543 - 문서 검색 문제해결
  minsun/BOJ/1543/sol.py
Labels: SOLVE, REVIEW, 민선

#210 [Solved] : SWEA/2112 보호필름 문제해결
  comet/SWEA/2112/sol.py
Labels: SOLVE, REVIEW, 혜성
